"""
FastAPI Router — Problem Generation

Mirrors the Express router pattern from the JS codebase.

Route:
    POST /api/v1/generate/problem

The route handler is a plain `def` (not `async def`) because the service
layer makes synchronous calls to voyageai and astrapy (both are sync SDKs).
FastAPI automatically offloads sync handlers to a thread pool, so the
event loop is never blocked.
"""

from fastapi import APIRouter
from fastapi.responses import JSONResponse
from pydantic import BaseModel, field_validator

from app.services.question_generator import generate_and_save_problem
from app.errors.base_error import BaseError
from app.utils.logger import get_logger

logger = get_logger(__name__)

router = APIRouter(prefix="/api/v1", tags=["Problems"])


# ── Request schema ────────────────────────────────────────────────────────────

class GenerateRequest(BaseModel):
    """
    Pydantic model for the POST /generate/problem request body.

    Field-level validators perform basic normalisation (strip + lower) before
    the data reaches the service layer, so the service only ever sees clean input.
    This is the Python equivalent of express-validator middleware in the JS app.
    """

    topic: str
    difficulty: str

    @field_validator("topic", "difficulty", mode="before")
    @classmethod
    def must_be_non_blank(cls, value: str, info) -> str:
        if not isinstance(value, str) or not value.strip():
            raise ValueError(f'"{info.field_name}" must be a non-empty string.')
        return value.strip().lower()


# ── Route handler ─────────────────────────────────────────────────────────────

@router.post(
    "/generate/problem",
    summary="Generate or retrieve a coding problem",
    response_description=(
        "The problem object with a 'source' field indicating whether it was "
        "freshly generated by the LLM or served from the AstraDB cache."
    ),
)
def generate_problem(body: GenerateRequest):
    """
    **Generate or retrieve** a structured coding problem.

    - Validates `topic` and `difficulty`.
    - Searches AstraDB for a semantically similar existing problem.
    - If found (cosine similarity ≥ 0.88): returns it immediately (`source: "cache"`).
    - Otherwise: calls the Groq LLM → parses → embeds → stores → returns
      the new problem (`source: "generated"`).

    **Request body:**
    ```json
    { "topic": "binary search", "difficulty": "medium" }
    ```

    **Response:**
    ```json
    {
      "source": "generated",
      "problem": {
        "_id": "...",
        "title": "...",
        "description": "...",
        "difficulty": "medium",
        "testCases": [...],
        "editorial": "...",
        "topic": "binary search"
      }
    }
    ```
    """
    try:
        result = generate_and_save_problem(body.topic, body.difficulty)
        return JSONResponse(content=result, status_code=200)

    except BaseError as exc:
        logger.warning(f"[Route] BaseError {exc.status_code}: {exc.message}")
        return JSONResponse(content=exc.to_dict(), status_code=exc.status_code)

    except Exception as exc:
        logger.error(f"[Route] Unexpected error: {exc}", exc_info=True)
        return JSONResponse(
            content={"error": "An unexpected error occurred.", "detail": str(exc)},
            status_code=500,
        )
